#=======================================================
#4.2.2 Configure journald
#======================================================
---
- name: journald Hardening Configuration
  hosts: servers
  become: yes
  tasks:

    # 1. Ensure journald is not configured to receive logs from a remote client
    - name: Ensure journald is not configured to receive remote logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?ForwardToSyslog='
        line: 'ForwardToSyslog=yes'
        create: yes

    # 2. Ensure journald service is enabled
    - name: Ensure systemd-journald service is enabled and running
      systemd:
        name: systemd-journald
        enabled: yes
        state: started

    # 3. Ensure journald is configured to compress large log files
    - name: Ensure journald compresses large log files
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?Compress='
        line: 'Compress=yes'
        create: yes

    # 4. Ensure journald is configured to write logfiles to persistent disk
    - name: Ensure journald writes logs to persistent disk
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?Storage='
        line: 'Storage=persistent'
        create: yes

    # Restart journald to apply config changes
    - name: Restart systemd-journald
      systemd:
        name: systemd-journald
        state: restarted

  post_tasks:
    - name: Display remediation summary
      ansible.builtin.debug:
       msg:
          - "======================================================================"
          - "CIS RHEL 9 Journald Hardening Complete"
          - "======================================================================"
          - "Ensure journald is not configured to receive logs from a remote client : APPLIED "
          - "Ensure journald service is enabled : APPLIED "
          - "Ensure journald is configured to compress large log files : APPLIED"
          - "Ensure journald is configured to write logfiles to persistent disk : APPLIED"
          - "======================================================================"
