#===================================================
#User Accounts and Environment
#==================================================
---
- name: Password and Session Hardening
  hosts: servers
  become: yes
  tasks:

    # 1. Ensure password expiration is 365 days or less
    - name: Ensure password expiration is 365 days or less
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   365'
        create: yes

    # 2. Ensure minimum days between password changes is configured
    - name: Ensure minimum days between password changes is configured
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MIN_DAYS'
        line: 'PASS_MIN_DAYS   7'
        create: yes

    # 3. Ensure password expiration warning days is 7 or more
    - name: Ensure password expiration warning days is 7 or more
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_WARN_AGE'
        line: 'PASS_WARN_AGE   7'
        create: yes

    # 4. Ensure inactive password lock is 30 days or less
    - name: Ensure inactive password lock is 30 days or less
      lineinfile:
        path: /etc/default/useradd
        regexp: '^INACTIVE='
        line: 'INACTIVE=30'
        create: yes

    # 5. Ensure default user shell timeout is 900 seconds or less
    - name: Ensure default user shell timeout is 900 seconds or less
      copy:
        dest: /etc/profile.d/timeout.sh
        mode: '0644'
        content: |
          TMOUT=900
          readonly TMOUT
          export TMOUT

    # 6. Ensure default user umask is 027 or more restrictive
    - name: Ensure default user umask is 027 or more restrictive
      lineinfile:
        path: /etc/profile
        regexp: '^umask'
        line: 'umask 027'
  post_tasks:
    - name: Display remediation summary
      ansible.builtin.debug:
       msg:
          - "======================================================================"
          - "CIS RHEL 9 PASSWORD POLICY  Remediation Complete"
          - "======================================================================"
          - " Ensure password expiration is 365 days or less : APPLIED"
          - "Ensure minimum days between password changes is configured : APPLIED"
          - "Ensure password expiration warning days is 7 or more  : APPLIED"
          - "Ensure inactive password lock is 30 days or less : APPLIED "
          - "Ensure default user shell timeout is 900 seconds or less : APPLIED "
          - " Ensure default user umask is 027 or more restrictive : APPLIED "
          - "======================================================================"

